name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: true
      matrix:
        php: [5.5, 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0]

    name: PHP ${{ matrix.php }}/Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, fileinfo, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, ldap, intl
          tools: composer:v2
          coverage: none

      - name: Setup problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Setup composer
        run: |
            cp composer.json-dist composer.json
            composer require "kolab/net_ldap3:~1.1.1" --no-update

      - name: Fix PHPUnit for PHP8
        run: composer config platform.php 7.4
        if: matrix.php >= 8

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit -c tests/phpunit.xml

  browser_tests:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: true

    name: Browser Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, fileinfo, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, ldap, intl
          tools: composer:v2
          coverage: none

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Setup composer
        run: |
            cp composer.json-dist composer.json
            composer require "kolab/net_ldap3:~1.1.1" --no-update
            composer require "laravel/dusk:~6.9.0" --no-update

      - name: Fix PHPUnit for PHP8
        run: composer config platform.php 7.4
        if: matrix.php >= 8

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Roundcube configuration
        run: cp .github/config-test.inc.php config/config-test.inc.php

      - name: Setup NPM deps
      - run: |
            npm install --force -g less
            npm install --force -g less-plugin-clean-css
            npm install --force -g uglify-js

      - name: Execute tests
        run: |
            .github/setup.sh \
            && echo "TESTS_MODE: DESKTOP" \
            && TESTS_MODE=desktop vendor/bin/phpunit -c tests/Browser/phpunit.xml \
            && echo "TESTS_MODE: PHONE" \
            && TESTS_MODE=phone vendor/bin/phpunit -c tests/Browser/phpunit.xml \
            && echo "TESTS_MODE: TABLET" \
            && TESTS_MODE=tablet vendor/bin/phpunit -c tests/Browser/phpunit.xml
